### PR TITLE
Refactor bible command to handle long passages using chunked responses

### PR DESCRIPTION
**Pull request by LyubomirT**
This Pull Request modifies the code to implement chunking for the `/bible` command. In simple words, it splits everything into chunks (up to 5), with each being 4000 characters at max. Please let me know if something is wrong or if you'd like something changed.

### CODE REVIEW

**Comment by LyubomirT** [comment]
> I'll make sure to review everything & restart the bot if it works

Okay then, good luck. Happy to help! :)

**Review by Blue-Robin-Taken — CHANGES_REQUESTED** [review]
Ok so it looks great but I made a couple of changes:
```
@bot.slash_command(name="bible", description="Put in a bible verse!")
async def bible(ctx, passage: discord.Option(str, description="Choose a passage or verse!"), characters_per_embed:discord.Option(int, required=False, max_value=4096, min_value=10) = 2000):
    api = requests.get(f"https://bible-api.com/{passage}?translation=kjv&verse_numbers=true").json()
    SUP = str.maketrans("0123456789", "⁰¹²³⁴⁵⁶⁷⁸⁹")
    try:
        verses = api["verses"]
        end_text = ""
        for verse in verses:
            end_text += str(verse["verse"]).translate(SUP) + verse["text"]
        num_embeds = math.ceil(len(end_text) / characters_per_embed)

        if num_embeds > 5:
            await ctx.respond("Sorry, this passage is too long to print. Try changing the characters per embed amount.", ephemeral=True)
            return
        for i in range(0, num_embeds):
            start = i * characters_per_embed
            end = min((i+1) * characters_per_embed, len(end_text))
            embed = discord.Embed(
                title=f"Bible verse: {api['reference']} KJV",
                colour=discord.Colour.random(),
            )
            

            embed.description = end_text[start:end]
            if i == 0:
                embed.set_author(name="Sent by: " + ctx.author.name)
                await ctx.respond(embed=embed)
            else:
                embed.title=""
                await ctx.channel.send(embed=embed)
    except KeyError:
        await ctx.respond("Invalid request. If you think this is a mistake, please contact us in the bot's discord server.", ephemeral=True)
    except discord.errors.HTTPException:
        print("HTTP")
        await ctx.respond("Sorry, this passage is too long to print. Try changing the characters per embed amount.", ephemeral=True)
```
- Instead of sending a response each time, it sends it in multiple channel sends.
- It asks for a character per embed amount instead of always sending it in 5 embeds
- It allows for a lot more verses to be sent
- It's somewhat faster 

Let me know what you think

**Comment by LyubomirT** [comment]
@Blue-Robin-Taken Applied the changes, please have a look.

**Review by Blue-Robin-Taken — APPROVED** [review]

**Comment by Blue-Robin-Taken** [comment]
Thanks!

**Pull request merged**
